version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Debug
install:
  - cmd: git submodule update --init --recursive
before_build:
  - cmd: cmake -G "Visual Studio 14 2015 Win64" -C ci\appveyor\cache.cmake .
build:
  project: ab-vm.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: ctest -V -C Debug .
