version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Debug
shallow_clone: true
clone_depth: 1
before_build:
  - cmd: git submodule update --init --recursive
  - cmd: cmake -G "Visual Studio 14 2015 Win64"
build:
  project: ab.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: mkdir %TEST_RESULT_DIR%
  - cmd: ctest -V -C Debug
