platform: x64
configuration: Debug
shallow_clone: true
clone_depth: 1
before_build:
  - cmd: cmake -G "Visual Studio 14 2015 Win64" 
build:
  project: ab.sln
  parallel: true
test_script:
  - cmd: mkdir %TEST_RESULT_DIR%
  - cmd: ctest -V -C Debug
