addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libclang-3.4-dev
      - libnuma-dev
      - ninja-build
os:
  - linux
  - osx
language: cpp
cache: ccache
compiler:
  - clang
script:
  - ./ci/travis/build.sh
