addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libnuma-dev
      - libclang-3.4-dev
      - ninja-build
os:
  - linux
  - osx
language: cpp
cache: ccache
compiler:
  - clang
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -V
