name: build ab
on:
  - push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake libfmt-dev python3-pip ninja-build ragel
          sudo pip install pyyaml jinja2
      - name: checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Configure
        run: mkdir build && cd build && cmake -Wdev -GNinja -DAB_COLOR_DIAGNOSTICS=on ..
      - name: Build
        run: cd build && ninja
      - name: Test
        run: cd build && ctest -V
        env:
          GTEST_COLOR: yes
