name: build ab
on:
  - push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-9 g++-9 build-essential cmake libfmt-dev python3-pip ninja-build ragel
          sudo pip install pyyaml jinja2
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -Wdev -GNinja -C../ci/cache.cmake ..
      - name: Build
        run: cd build && ninja
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
        env:
          GTEST_COLOR: yes
