name: build-ab
on:
  - pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: configure
        run:
          - mkdir build
          - cmake -Wdev -S . -B build
      - name: build
        run: cmake --build build
      - name: test
        run: ctest -V ./build/
  
